/**
 * SQL template to create all tables in a tenant schema.
 * Replace __SCHEMA__ with the actual schema name (e.g. t_abc12def).
 */
export function getTenantSchemaSql(schemaName: string): string[] {
  const s = `"${schemaName.replace(/"/g, '""')}"`;
  return [
    `CREATE SCHEMA IF NOT EXISTS ${s}`,
    `CREATE TABLE IF NOT EXISTS ${s}.users (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      username character varying(100) NOT NULL,
      "passwordHash" character varying(255) NOT NULL,
      email character varying(200),
      "firstName" character varying(100),
      "lastName" character varying(100),
      phone character varying(20),
      role character varying(30) DEFAULT 'restaurant_staff',
      "isActive" boolean DEFAULT true,
      "lastLoginAt" TIMESTAMP,
      "lastLoginIp" character varying(45),
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
      "deletedAt" TIMESTAMP,
      PRIMARY KEY (id),
      UNIQUE (username)
    )`,
    `CREATE TABLE IF NOT EXISTS ${s}.categories (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      name character varying(100) NOT NULL,
      "nameKo" character varying(100) NOT NULL,
      icon character varying(10),
      description text,
      "descriptionKo" text,
      "isActive" boolean DEFAULT true,
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
      "deletedAt" TIMESTAMP,
      PRIMARY KEY (id)
    )`,
    `CREATE TABLE IF NOT EXISTS ${s}.products (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      name character varying(200) NOT NULL,
      "nameKo" character varying(200) NOT NULL,
      "addName" character varying(200),
      "addNameKo" character varying(200),
      price numeric(10,2) NOT NULL,
      description text,
      "descriptionKo" text,
      image character varying(500),
      "categoryId" uuid,
      category character varying(100),
      "categoryKo" character varying(100),
      available boolean DEFAULT true,
      sales integer DEFAULT 0,
      visible boolean DEFAULT true,
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
      "deletedAt" TIMESTAMP,
      PRIMARY KEY (id),
      CONSTRAINT "FK_products_category" FOREIGN KEY ("categoryId") REFERENCES ${s}.categories(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS ${s}.product_categories (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      "productId" uuid NOT NULL,
      "categoryId" uuid NOT NULL,
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
      PRIMARY KEY (id),
      CONSTRAINT "FK_pc_product" FOREIGN KEY ("productId") REFERENCES ${s}.products(id) ON DELETE CASCADE,
      CONSTRAINT "FK_pc_category" FOREIGN KEY ("categoryId") REFERENCES ${s}.categories(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS ${s}.tables (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      name character varying(100) NOT NULL,
      "tableNumber" integer NOT NULL,
      "qrCodeUrl" character varying(500),
      "qrCodeImagePath" character varying(500),
      "orderUrl" character varying(500),
      "qrUuid" uuid,
      status character varying(20) NOT NULL DEFAULT 'available',
      capacity integer DEFAULT 0,
      description text,
      "isActive" boolean DEFAULT true,
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
      "deletedAt" TIMESTAMP,
      PRIMARY KEY (id),
      UNIQUE ("tableNumber")
    )`,
    `CREATE TABLE IF NOT EXISTS ${s}.orders (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      "orderNumber" character varying(100) NOT NULL,
      "customerName" character varying(100) NOT NULL,
      "customerPhone" character varying(20),
      "customerAddress" character varying(200),
      notes text,
      subtotal numeric(10,2) NOT NULL,
      tax numeric(10,2) DEFAULT 0,
      "deliveryFee" numeric(10,2) DEFAULT 0,
      total numeric(10,2) NOT NULL,
      status character varying(30) NOT NULL DEFAULT 'pending',
      "orderType" character varying(20) NOT NULL DEFAULT 'dine_in',
      "tableId" uuid,
      "tableNumber" integer,
      "estimatedDeliveryTime" TIMESTAMP,
      "actualDeliveryTime" TIMESTAMP,
      "paymentStatus" character varying(20) NOT NULL DEFAULT 'unpaid',
      "paymentMethod" character varying(30),
      "stripeCheckoutSessionId" character varying(255),
      "stripePaymentIntentId" character varying(255),
      "sepayTransactionId" character varying(64),
      "sepayReferenceCode" character varying(255),
      "paidAt" TIMESTAMP,
      "voucherId" uuid,
      "voucherCode" character varying(50),
      "voucherDiscount" numeric(10,2) NOT NULL DEFAULT 0,
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
      "deletedAt" TIMESTAMP,
      PRIMARY KEY (id),
      UNIQUE ("orderNumber"),
      CONSTRAINT "FK_orders_table" FOREIGN KEY ("tableId") REFERENCES ${s}.tables(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS ${s}.vouchers (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      code character varying(50) NOT NULL,
      name character varying(200) NOT NULL,
      "nameKo" character varying(200),
      description text,
      type character varying(20) NOT NULL DEFAULT 'percentage',
      "discountValue" numeric(10,2) NOT NULL DEFAULT 0,
      "productId" uuid,
      "minOrderAmount" numeric(10,2) NOT NULL DEFAULT 0,
      "maxDiscountAmount" numeric(10,2),
      "totalUsageLimit" integer,
      "perUserLimit" integer NOT NULL DEFAULT 1,
      "usedCount" integer NOT NULL DEFAULT 0,
      "validFrom" TIMESTAMP,
      "validUntil" TIMESTAMP,
      "isActive" boolean NOT NULL DEFAULT true,
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
      "deletedAt" TIMESTAMP,
      PRIMARY KEY (id)
    )`,
    `CREATE UNIQUE INDEX IF NOT EXISTS "IDX_vouchers_code" ON ${s}.vouchers (code) WHERE "deletedAt" IS NULL`,
    `CREATE TABLE IF NOT EXISTS ${s}.product_promotions (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      name character varying(200) NOT NULL,
      scope character varying(20) NOT NULL DEFAULT 'product',
      "promotionType" character varying(20) NOT NULL DEFAULT 'standard',
      "timeStart" character varying(5),
      "timeEnd" character varying(5),
      "daysOfWeek" character varying(30),
      "buyQuantity" integer,
      "getQuantity" integer,
      "rewardProductId" uuid,
      "productId" uuid,
      "categoryId" uuid,
      "discountMode" character varying(20) NOT NULL DEFAULT 'percentage',
      "discountValue" numeric(10,2) NOT NULL,
      "maxDiscountAmount" numeric(10,2),
      "validFrom" TIMESTAMP NOT NULL,
      "validUntil" TIMESTAMP NOT NULL,
      priority integer NOT NULL DEFAULT 0,
      "isActive" boolean NOT NULL DEFAULT true,
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
      "deletedAt" TIMESTAMP,
      PRIMARY KEY (id)
    )`,
    `CREATE TABLE IF NOT EXISTS ${s}.combos (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      name character varying(200) NOT NULL,
      "nameKo" character varying(200),
      description text,
      "descriptionKo" text,
      price numeric(10,2) NOT NULL,
      image character varying(500),
      "validFrom" TIMESTAMP,
      "validUntil" TIMESTAMP,
      "sortOrder" integer NOT NULL DEFAULT 0,
      "isActive" boolean NOT NULL DEFAULT true,
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
      "deletedAt" TIMESTAMP,
      PRIMARY KEY (id)
    )`,
    `CREATE TABLE IF NOT EXISTS ${s}.combo_items (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      "comboId" uuid NOT NULL,
      "productId" uuid NOT NULL,
      quantity integer NOT NULL DEFAULT 1,
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
      PRIMARY KEY (id),
      CONSTRAINT "FK_combo_items_combo" FOREIGN KEY ("comboId") REFERENCES ${s}.combos(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS ${s}.order_items (
      id uuid NOT NULL DEFAULT gen_random_uuid(),
      "orderId" uuid NOT NULL,
      "productId" uuid NOT NULL,
      "productName" character varying(200) NOT NULL,
      "unitPrice" numeric(10,2) NOT NULL,
      quantity integer NOT NULL,
      "totalPrice" numeric(10,2) NOT NULL,
      "specialInstructions" text,
      "originalUnitPrice" numeric(10,2),
      "promotionId" uuid,
      "promotionDiscount" numeric(10,2) NOT NULL DEFAULT 0,
      "comboId" uuid,
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
      PRIMARY KEY (id),
      CONSTRAINT "FK_oi_order" FOREIGN KEY ("orderId") REFERENCES ${s}.orders(id) ON DELETE CASCADE,
      CONSTRAINT "FK_oi_product" FOREIGN KEY ("productId") REFERENCES ${s}.products(id) ON DELETE RESTRICT
    )`,
  ];
}
