import { DataSource } from 'typeorm';
import { Category } from '../entities/category.entity';
import { Product } from '../entities/product.entity';

export default async function seed(dataSource: DataSource): Promise<void> {
    const categoryRepository = dataSource.getRepository(Category);
    const productRepository = dataSource.getRepository(Product);

    console.log('Starting database seeding...');

    // All categories from app.service.ts - removed hardcoded IDs since entity uses auto-generated UUIDs
    const categories = [
        {
            "name": "Cơm Xôi",
            "nameKo": "찹쌀",
            "icon": "🍚",
            "description": "Cơm và xôi theo phong cách Việt",
            "descriptionKo": "베트남식 밥과 찹쌀",
            "isActive": true,
            "createdAt": new Date("2025-07-21 11:18:52.673050"),
            "updatedAt": new Date("2025-07-21 11:18:52.673055")
        },
        {
            "name": "Phở",
            "nameKo": "면",
            "icon": "🍜",
            "description": "Phở và các món nước",
            "descriptionKo": "쌀국수 및 국수류",
            "isActive": true,
            "createdAt": new Date("2025-07-21 11:18:52.673058"),
            "updatedAt": new Date("2025-07-21 11:18:52.673058")
        },
        {
            "name": "Bún",
            "nameKo": "면",
            "icon": "🍝",
            "description": "Bún và món ăn kèm",
            "descriptionKo": "분짜, 분다우 등 면 요리",
            "isActive": true,
            "createdAt": new Date("2025-07-21 11:18:52.673060"),
            "updatedAt": new Date("2025-07-21 11:18:52.673060")
        },
        {
            "name": "Nhậu",
            "nameKo": "안주",
            "icon": "🍢",
            "description": "Món nhậu, đồ ăn chơi",
            "descriptionKo": "술안주 및 간식",
            "isActive": true,
            "createdAt": new Date("2025-07-21 11:18:52.673062"),
            "updatedAt": new Date("2025-07-21 11:18:52.673062")
        },
        {
            "name": "Ăn Chơi",
            "nameKo": "사이드",
            "icon": "🍟",
            "description": "Món ăn vặt, phụ",
            "descriptionKo": "사이드 메뉴",
            "isActive": true,
            "createdAt": new Date("2025-07-21 11:18:52.673064"),
            "updatedAt": new Date("2025-07-21 11:18:52.673064")
        },
        {
            "name": "Bánh Mỳ - Nộm",
            "nameKo": "빵·샐러드",
            "icon": "🥖",
            "description": "Bánh mì và các loại nộm",
            "descriptionKo": "샌드위치와 샐러드",
            "isActive": true,
            "createdAt": new Date("2025-07-21 11:18:52.673066"),
            "updatedAt": new Date("2025-07-21 11:18:52.673067")
        },
        {
            "name": "Lẩu",
            "nameKo": "샤브샤브",
            "icon": "🍲",
            "description": "Các loại lẩu",
            "descriptionKo": "샤브샤브",
            "isActive": true,
            "createdAt": new Date("2025-07-21 11:18:52.673068"),
            "updatedAt": new Date("2025-07-21 11:18:52.673069")
        },
        {
            "name": "Đồ Uống",
            "nameKo": "음료",
            "icon": "🥤",
            "description": "Nước ngọt và bia rượu",
            "descriptionKo": "음료 및 주류",
            "isActive": true,
            "createdAt": new Date("2025-07-21 11:18:52.673072"),
            "updatedAt": new Date("2025-07-21 11:18:52.673073")
        },
        {
            "name": "Set Menu",
            "nameKo": "세트메뉴",
            "icon": "📦",
            "description": "Thực đơn theo set",
            "descriptionKo": "세트 메뉴",
            "isActive": true,
            "createdAt": new Date("2025-07-21 11:18:52.673075"),
            "updatedAt": new Date("2025-07-21 11:18:52.673075")
        }
    ];

    // Store category IDs for product seeding
    const categoryIdMap = new Map<string, string>();

    for (const categoryData of categories) {
        // Check if category exists by name instead of ID since IDs are auto-generated
        const existingCategory = await categoryRepository.findOne({ where: { name: categoryData.name } });
        if (!existingCategory) {
            const category = categoryRepository.create(categoryData);
            const savedCategory = await categoryRepository.save(category);
            console.log(`Created category: ${category.name}`);
            // Store the auto-generated ID for product seeding
            categoryIdMap.set(categoryData.name, savedCategory.id);
        } else {
            console.log(`Category already exists: ${existingCategory.name}`);
            // Store the existing ID for product seeding
            categoryIdMap.set(categoryData.name, existingCategory.id);
        }
    }

    // All products from app.service.ts - removed hardcoded IDs since entity uses auto-generated UUIDs
    const products = [
        {
            "name": "Cơm Rang Dưa Bò",
            "nameKo": "김치 볶음 밥",
            "addName": "Cơm Rang Dưa Bò",
            "addNameKo": "김치 볶음 밥",
            "price": 10000,
            "description": "Cơm rang với dưa bò thơm ngon",
            "descriptionKo": "베트남 김치, 소고기를 넣어서 만든 볶음밥",
            "image": "/images/com-rang-dua-bo.png",
            "category": "Cơm Xôi",
            "categoryKo": "찹쌀",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.904089"),
            "updatedAt": new Date("2025-07-21 11:10:46.904092")
        },
        {
            "name": "Cơm Gà",
            "nameKo": "치킨밥",
            "addName": "Cơm Gà",
            "addNameKo": "치킨밥",
            "price": 10000,
            "description": "Cơm gà với đùi gà, rau và sốt",
            "descriptionKo": "닭 다리, 소스, 야채 같이 나옵니다",
            "image": "/images/com-ga.png",
            "category": "Cơm Xôi",
            "categoryKo": "찹쌀",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.904271"),
            "updatedAt": new Date("2025-07-21 11:10:46.904274")
        },
        {
            "name": "Cơm Sườn",
            "nameKo": "껌스언",
            "addName": "Cơm Sườn",
            "addNameKo": "껌스언",
            "price": 10500,
            "description": "Cơm với sườn heo nướng",
            "descriptionKo": "돼지갈비 덮밥",
            "image": "/images/com-suon.png",
            "category": "Cơm Xôi",
            "categoryKo": "찹쌀",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.904692"),
            "updatedAt": new Date("2025-07-21 11:10:46.904694")
        },
        {
            "name": "Cơm Rang Hải Sản",
            "nameKo": "해산물 볶음밥",
            "addName": "Cơm Rang Hải Sản",
            "addNameKo": "해산물 볶음밥",
            "price": 10000,
            "description": "Cơm rang hải sản tổng hợp",
            "descriptionKo": "모듬 해산물로 만든 볶음밥",
            "image": "/images/com-rang-hai-san.png",
            "category": "Cơm Xôi",
            "categoryKo": "찹쌀",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.904826"),
            "updatedAt": new Date("2025-07-21 11:10:46.904829")
        },
        {
            "name": "Tôm Rim",
            "nameKo": "왕새우 덮밥",
            "addName": "Tôm Rim",
            "addNameKo": "왕새우 덮밥",
            "price": 10000,
            "description": "Tôm rim với sốt đặc biệt",
            "descriptionKo": "싱싱한 새우와 맛있는 소스를 넣어 만든 음식",
            "image": "/images/tom-rim.png",
            "category": "Cơm Xôi",
            "categoryKo": "찹쌀",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.905141"),
            "updatedAt": new Date("2025-07-21 11:10:46.905143")
        },
        {
            "name": "Xôi Thập Cẩm",
            "nameKo": "모듬 찹쌀",
            "addName": "Xôi Thập Cẩm",
            "addNameKo": "모듬 찹쌀",
            "price": 13000,
            "description": "Xôi thập cẩm truyền thống",
            "descriptionKo": "베트남 식으로 요리한 모듬 찹쌀",
            "image": "/images/xoi-thap-cam.png",
            "category": "Cơm Xôi",
            "categoryKo": "찹쌀",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.905366"),
            "updatedAt": new Date("2025-07-21 11:10:46.905367")
        },
        {
            "name": "Mẹt Gà",
            "nameKo": "치킨 모듬",
            "addName": "Mẹt Gà",
            "addNameKo": "치킨 모듬",
            "price": 40000,
            "description": "Xôi, salad gà, gà rang muối, chân gà, cánh gà, khoai tây chiên",
            "descriptionKo": "찹쌀, 치킨 샐러드, 치킨소금튀김, 양념 닭발, 양념윙, 감자튀김",
            "image": "/images/met-ga.png",
            "category": "Cơm Xôi",
            "categoryKo": "찹쌀",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.905378"),
            "updatedAt": new Date("2025-07-21 11:10:46.905378")
        },
        {
            "name": "Bún Bò Huế",
            "nameKo": "분버후에",
            "addName": "Bún Bò Huế",
            "addNameKo": "분버후에",
            "price": 12000,
            "description": "Bún bò Huế cay đậm đà với hương vị truyền thống",
            "descriptionKo": "파인애플, 레몬그라스, 피쉬소스로 만든 국물로 매콤, 달콤한 맛이 납니다",
            "image": "/images/bun-bo-hue.png",
            "category": "Phở",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.905581"),
            "updatedAt": new Date("2025-07-21 11:10:46.905582")
        },
        {
            "name": "Phở Bò",
            "nameKo": "소고기 쌀국수",
            "addName": "Phở Bò",
            "addNameKo": "소고기 쌀국수",
            "price": 9500,
            "description": "Phở bò truyền thống với nước dùng đậm đà",
            "descriptionKo": "소고기 쌀국수",
            "image": "/images/pho-bo.png",
            "category": "Phở",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.905600"),
            "updatedAt": new Date("2025-07-21 11:10:46.905600")
        },
        {
            "name": "Chả Ram Tôm Đất",
            "nameKo": "새우 짜조",
            "addName": "Chả Ram Tôm Đất",
            "addNameKo": "새우 짜조",
            "price": 7500,
            "description": "Chả ram nhỏ cuốn tôm, giòn tan",
            "descriptionKo": "작은 새우로 만든 짜조, 4개",
            "image": "/images/cha-ram-tom.png",
            "category": "Phở",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.905615"),
            "updatedAt": new Date("2025-07-21 11:10:46.905616")
        },
        {
            "name": "Gỏi Cuốn",
            "nameKo": "월남쌈",
            "addName": "Gỏi Cuốn",
            "addNameKo": "월남쌈",
            "price": 6000,
            "description": "Gỏi cuốn tươi với rau, tôm, bún",
            "descriptionKo": "새우와 채소가 들어간 월남쌈, 3개",
            "image": "/images/goi-cuon.png",
            "category": "Phở",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.905625"),
            "updatedAt": new Date("2025-07-21 11:10:46.905625")
        },
        {
            "name": "Tôm Viên Chiên",
            "nameKo": "새우볼 튀김",
            "addName": "Tôm Viên Chiên",
            "addNameKo": "새우볼 튀김",
            "price": 6000,
            "description": "Tôm viên chiên giòn hấp dẫn",
            "descriptionKo": "새우볼 튀김 5개",
            "image": "/images/tom-vien-chien.png",
            "category": "Phở",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.905665"),
            "updatedAt": new Date("2025-07-21 11:10:46.905667")
        },
        {
            "name": "Tôm Chiên Xù",
            "nameKo": "왕새우 튀김",
            "addName": "Tôm Chiên Xù",
            "addNameKo": "왕새우 튀김",
            "price": 6000,
            "description": "Tôm chiên xù giòn tan",
            "descriptionKo": "왕새우 튀김 4개",
            "image": "/images/tom-chien-xu.png",
            "category": "Phở",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.905698"),
            "updatedAt": new Date("2025-07-21 11:10:46.905698")
        },
        {
            "name": "Chả Giò",
            "nameKo": "짜조",
            "addName": "Chả Giò",
            "addNameKo": "짜조",
            "price": 7000,
            "description": "Chả giò truyền thống giòn tan",
            "descriptionKo": "짜조 4개",
            "image": "/images/cha-gio.png",
            "category": "Phở",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:10:46.905714"),
            "updatedAt": new Date("2025-07-21 11:10:46.905715")
        },
        {
            "name": "Bánh Xèo",
            "nameKo": "반쎄오",
            "addName": "Bánh Xèo",
            "addNameKo": "반쎄오",
            "price": 14500,
            "description": "Bánh xèo giòn rụm với nhân rau và hải sản",
            "descriptionKo": "쌀가루 반죽에 각종 채소, 해산물을 넣어 반달 모양으로 부쳐낸 베트남 음식입니다",
            "image": "/images/banh-xeo.png",
            "category": "Bún",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:12:18.312732"),
            "updatedAt": new Date("2025-07-21 11:12:18.312736")
        },
        {
            "name": "Mẹt Nem Lụi",
            "nameKo": "냄루이",
            "addName": "Mẹt Nem Lụi",
            "addNameKo": "냄루이",
            "price": 14000,
            "description": "Nem lụi nướng xiên với rau sống và bún",
            "descriptionKo": "소시지 모양 돼지고기를 레몬그라스 막대에 꽂아 구워서 면과 함께 먹는 음식",
            "image": "/images/nem-lui.png",
            "category": "Bún",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:12:18.313221"),
            "updatedAt": new Date("2025-07-21 11:12:18.313225")
        },
        {
            "name": "Bún Thịt Nướng",
            "nameKo": "분짜",
            "addName": "Bún Thịt Nướng",
            "addNameKo": "분짜",
            "price": 12000,
            "description": "Bún thịt nướng với rau sống, đồ chua",
            "descriptionKo": "숯불고기, 채소와 함께 먹는 분짜",
            "image": "/images/bun-thit-nuong.png",
            "category": "Bún",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:12:18.313591"),
            "updatedAt": new Date("2025-07-21 11:12:18.313594")
        },
        {
            "name": "Bún Đậu",
            "nameKo": "분다우",
            "addName": "Bún Đậu",
            "addNameKo": "분다우",
            "price": 12500,
            "description": "Bún đậu mắm tôm với chả cốm, đậu hũ",
            "descriptionKo": "족발, 두부, 순대, 햄, 면, 야채와 함께 먹는 마암돔 소스 요리",
            "image": "/images/bun-dau-mam-tom.png",
            "category": "Bún",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:12:18.314583"),
            "updatedAt": new Date("2025-07-21 11:12:18.314586")
        },
        {
            "name": "Nem Nướng Nha Trang",
            "nameKo": "냄누엉 나짱",
            "addName": "Nem Nướng Nha Trang",
            "addNameKo": "냄누엉 나짱",
            "price": 13000,
            "description": "Nem nướng Nha Trang kèm rau và bún",
            "descriptionKo": "숯불에 구운 돼지고기와 면, 채소를 함께 먹는 음식",
            "image": "/images/nem-nuong-nha-trang.png",
            "category": "Bún",
            "categoryKo": "면",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:12:18.314680"),
            "updatedAt": new Date("2025-07-21 11:12:18.314682")
        },
        {
            "name": "Mực Chiên Xù",
            "nameKo": "오징어 튀김",
            "addName": "Mực Chiên Xù",
            "addNameKo": "오징어 튀김",
            "price": 13000,
            "description": "Mực chiên xù giòn rụm",
            "descriptionKo": "바삭한 오징어 튀김",
            "image": "/images/muc-chien-xu.png",
            "category": "Nhậu",
            "categoryKo": "안주",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.081988"),
            "updatedAt": new Date("2025-07-21 11:14:00.081992")
        },
        {
            "name": "Tôm Sốt Bơ Tỏi",
            "nameKo": "새우 버터마늘볶음",
            "addName": "Tôm Sốt Bơ Tỏi",
            "addNameKo": "새우 버터마늘볶음",
            "price": 16000,
            "description": "Tôm sốt bơ tỏi thơm ngon",
            "descriptionKo": "마늘, 버터, 새우 같이 볶음",
            "image": "/images/tom-sot-bo-toi.png",
            "category": "Nhậu",
            "categoryKo": "안주",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.082145"),
            "updatedAt": new Date("2025-07-21 11:14:00.082149")
        },
        {
            "name": "Dồi Sụn Chiên",
            "nameKo": "순대 튀김",
            "addName": "Dồi Sụn Chiên",
            "addNameKo": "순대 튀김",
            "price": 14000,
            "description": "Dồi sụn chiên giòn đặc biệt",
            "descriptionKo": "순대를 바삭하게 튀긴 요리",
            "image": "/images/doi-sun-chien.png",
            "category": "Nhậu",
            "categoryKo": "안주",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.082288"),
            "updatedAt": new Date("2025-07-21 11:14:00.082289")
        },
        {
            "name": "Ngao Hấp Thái",
            "nameKo": "조개 타이 찜",
            "addName": "Ngao Hấp Thái",
            "addNameKo": "조개 타이 찜",
            "price": 14000,
            "description": "Ngao hấp vị Thái chua cay",
            "descriptionKo": "조개, 파인애플, 레몬그라스를 넣은 매콤달콤 찜",
            "image": "/images/ngao-hap-thai.png",
            "category": "Nhậu",
            "categoryKo": "안주",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.082464"),
            "updatedAt": new Date("2025-07-21 11:14:00.082466")
        },
        {
            "name": "Gà Rang Muối",
            "nameKo": "치킨 소금 볶음",
            "addName": "Gà Rang Muối",
            "addNameKo": "치킨 소금 볶음",
            "price": 18000,
            "description": "Gà rang muối giòn và đậm vị",
            "descriptionKo": "치킨 튀김 후 맛소금으로 볶음",
            "image": "/images/ga-rang-muoi.png",
            "category": "Nhậu",
            "categoryKo": "안주",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.083046"),
            "updatedAt": new Date("2025-07-21 11:14:00.083050")
        },
        {
            "name": "Lòng Xào Dưa",
            "nameKo": "내장 김치 볶음",
            "addName": "Lòng Xào Dưa",
            "addNameKo": "내장 김치 볶음",
            "price": 15000,
            "description": "Lòng xào với dưa chua",
            "descriptionKo": "김치와 함께 볶은 돼지 내장",
            "image": "/images/long-xao-dua.png",
            "category": "Nhậu",
            "categoryKo": "안주",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.083132"),
            "updatedAt": new Date("2025-07-21 11:14:00.083135")
        },
        {
            "name": "Tràng Luộc",
            "nameKo": "창자 삶은 요리",
            "addName": "Tràng Luộc",
            "addNameKo": "창자 삶은 요리",
            "price": 15000,
            "description": "Tràng heo luộc mềm",
            "descriptionKo": "삶은 돼지창자",
            "image": "/images/trang-luoc.png",
            "category": "Nhậu",
            "categoryKo": "안주",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.083218"),
            "updatedAt": new Date("2025-07-21 11:14:00.083219")
        },
        {
            "name": "Mực Khô Nướng",
            "nameKo": "마른 오징어 구이",
            "addName": "Mực Khô Nướng",
            "addNameKo": "마른 오징어 구이",
            "price": 15000,
            "description": "Mực khô nướng thơm",
            "descriptionKo": "불에 구운 마른 오징어",
            "image": "/images/muc-kho-nuong.png",
            "category": "Ăn Chơi",
            "categoryKo": "사이드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.083678"),
            "updatedAt": new Date("2025-07-21 11:14:00.083681")
        },
        {
            "name": "Khoai Tây Chiên",
            "nameKo": "감자 튀김",
            "addName": "Khoai Tây Chiên",
            "addNameKo": "감자 튀김",
            "price": 9000,
            "description": "Khoai tây chiên giòn",
            "descriptionKo": "바삭한 감자튀김",
            "image": "/images/khoai-tay-chien.png",
            "category": "Ăn Chơi",
            "categoryKo": "사이드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.084209"),
            "updatedAt": new Date("2025-07-21 11:14:00.084212")
        },
        {
            "name": "Ngô Chiên",
            "nameKo": "옥수수 튀김",
            "addName": "Ngô Chiên",
            "addNameKo": "옥수수 튀김",
            "price": 6000,
            "description": "Ngô chiên bơ giòn",
            "descriptionKo": "버터와 함께 튀긴 옥수수",
            "image": "/images/ngo-chien.png",
            "category": "Ăn Chơi",
            "categoryKo": "사이드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.084324"),
            "updatedAt": new Date("2025-07-21 11:14:00.084328")
        },
        {
            "name": "Đậu Lướt Ván",
            "nameKo": "두부 튀김",
            "addName": "Đậu Lướt Ván",
            "addNameKo": "두부 튀김",
            "price": 6000,
            "description": "Đậu hũ chiên vàng",
            "descriptionKo": "노릇하게 튀긴 두부",
            "image": "/images/dau-luot-van.png",
            "category": "Ăn Chơi",
            "categoryKo": "사이드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.084375"),
            "updatedAt": new Date("2025-07-21 11:14:00.084377")
        },
        {
            "name": "Xoài Dầm",
            "nameKo": "그린망고 무침",
            "addName": "Xoài Dầm",
            "addNameKo": "그린망고 무침",
            "price": 12000,
            "description": "Xoài xanh dầm mắm đường",
            "descriptionKo": "새콤달콤 그린망고 무침",
            "image": "/images/xoai-dam.png",
            "category": "Ăn Chơi",
            "categoryKo": "사이드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.084489"),
            "updatedAt": new Date("2025-07-21 11:14:00.084492")
        },
        {
            "name": "Bánh Đa",
            "nameKo": "쌀 과자",
            "addName": "Bánh Đa",
            "addNameKo": "쌀 과자",
            "price": 1500,
            "description": "Bánh đa nướng",
            "descriptionKo": "바삭한 쌀과자",
            "image": "/images/banh-da.png",
            "category": "Ăn Chơi",
            "categoryKo": "사이드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.084547"),
            "updatedAt": new Date("2025-07-21 11:14:00.084550")
        },
        {
            "name": "Bò Khô",
            "nameKo": "육포",
            "addName": "Bò Khô",
            "addNameKo": "육포",
            "price": 10000,
            "description": "Bò khô cay thơm",
            "descriptionKo": "매콤한 육포",
            "image": "/images/bo-kho.png",
            "category": "Ăn Chơi",
            "categoryKo": "사이드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.084603"),
            "updatedAt": new Date("2025-07-21 11:14:00.084606")
        },
        {
            "name": "Lạc Rang",
            "nameKo": "땅콩",
            "addName": "Lạc Rang",
            "addNameKo": "땅콩",
            "price": 5000,
            "description": "Lạc rang giòn",
            "descriptionKo": "볶은 땅콩",
            "image": "/images/lac-rang.png",
            "category": "Ăn Chơi",
            "categoryKo": "사이드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:00.084628"),
            "updatedAt": new Date("2025-07-21 11:14:00.084629")
        },
        {
            "name": "Bánh Mì Thịt, Trứng",
            "nameKo": "고기 반미",
            "addName": "Bánh Mì Thịt, Trứng",
            "addNameKo": "고기 반미",
            "price": 8000,
            "description": "Bánh mì với thịt, trứng, rau",
            "descriptionKo": "야채, 오이, 고기, 계란 등이 들어간 반미",
            "image": "/images/banh-mi-thit.png",
            "category": "Bánh Mỳ - Nộm",
            "categoryKo": "빵·샐러드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:59.448337"),
            "updatedAt": new Date("2025-07-21 11:14:59.448341")
        },
        {
            "name": "Ba Tê",
            "nameKo": "반미바대",
            "addName": "Ba Tê",
            "addNameKo": "반미바대",
            "price": 8000,
            "description": "Bánh mì ba tê với rau",
            "descriptionKo": "간, 우유, 고기, 버터 등으로 만든 바대와 야채가 들어간 반미",
            "image": "/images/ba-te.png",
            "category": "Bánh Mỳ - Nộm",
            "categoryKo": "빵·샐러드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:59.448684"),
            "updatedAt": new Date("2025-07-21 11:14:59.448687")
        },
        {
            "name": "Bò Né",
            "nameKo": "스테이크방",
            "addName": "Bò Né",
            "addNameKo": "스테이크방",
            "price": 11500,
            "description": "Bò né kèm trứng và bánh mì",
            "descriptionKo": "생 고기, 계란, 베트남 소스로 만든 스테이크",
            "image": "/images/bo-ne.png",
            "category": "Bánh Mỳ - Nộm",
            "categoryKo": "빵·샐러드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:59.448738"),
            "updatedAt": new Date("2025-07-21 11:14:59.448739")
        },
        {
            "name": "Rau Muống Xào",
            "nameKo": "모닝글로리 볶음",
            "addName": "Rau Muống Xào",
            "addNameKo": "모닝글로리 볶음",
            "price": 9000,
            "description": "Rau muống xào tỏi thơm ngon",
            "descriptionKo": "모닝글로리를 마늘과 함께 볶은 요리",
            "image": "/images/rau-muong-xao.png",
            "category": "Bánh Mỳ - Nộm",
            "categoryKo": "빵·샐러드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:59.449068"),
            "updatedAt": new Date("2025-07-21 11:14:59.449071")
        },
        {
            "name": "Gỏi Hải Sản",
            "nameKo": "해산물 샐러드",
            "addName": "Gỏi Hải Sản",
            "addNameKo": "해산물 샐러드",
            "price": 15000,
            "description": "Gỏi hải sản tươi mát",
            "descriptionKo": "새우, 오징어, 당근, 오이, 양파 등이 들어간 샐러드",
            "image": "/images/goi-hai-san.png",
            "category": "Bánh Mỳ - Nộm",
            "categoryKo": "빵·샐러드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:59.449343"),
            "updatedAt": new Date("2025-07-21 11:14:59.449346")
        },
        {
            "name": "Nộm Gà",
            "nameKo": "치킨 샐러드",
            "addName": "Nộm Gà",
            "addNameKo": "치킨 샐러드",
            "price": 15000,
            "description": "Nộm gà với rau và đậu phộng",
            "descriptionKo": "당근, 오이, 양파, 당콩, 치킨 등이 들어간 샐러드",
            "image": "/images/nom-ga.png",
            "category": "Bánh Mỳ - Nộm",
            "categoryKo": "빵·샐러드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:59.449397"),
            "updatedAt": new Date("2025-07-21 11:14:59.449400")
        },
        {
            "name": "Chân Gà Sốt Thái",
            "nameKo": "무뼈닭발 무침",
            "addName": "Chân Gà Sốt Thái",
            "addNameKo": "무뼈닭발 무침",
            "price": 15000,
            "description": "Chân gà rút xương sốt Thái",
            "descriptionKo": "무뼈 닭발을 태국 스타일로 무침",
            "image": "/images/chan-ga-sot-thai.png",
            "category": "Bánh Mỳ - Nộm",
            "categoryKo": "빵·샐러드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:59.449428"),
            "updatedAt": new Date("2025-07-21 11:14:59.449428")
        },
        {
            "name": "Bánh Phồng Tôm",
            "nameKo": "뻥튀기 새우칩",
            "addName": "Bánh Phồng Tôm",
            "addNameKo": "뻥튀기 새우칩",
            "price": 5000,
            "description": "Bánh phồng tôm giòn",
            "descriptionKo": "튀긴 새우칩",
            "image": "/images/banh-phong-tom.png",
            "category": "Bánh Mỳ - Nộm",
            "categoryKo": "빵·샐러드",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:14:59.449438"),
            "updatedAt": new Date("2025-07-21 11:14:59.449439")
        },
        {
            "name": "Lẩu Thái",
            "nameKo": "타이샤브샤브",
            "addName": "Lẩu Thái",
            "addNameKo": "타이샤브샤브",
            "price": 43000,
            "description": "Lẩu Thái chua cay với hải sản, thịt, rau",
            "descriptionKo": "매콤달콤 국물, 다양한 야채, 소고기, 두부, 새우, 버섯, 조개, 쭈꾸미, 치킨, 옥수수, 라면",
            "image": "/images/lau-thai.png",
            "category": "Lẩu",
            "categoryKo": "샤브샤브",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.504370"),
            "updatedAt": new Date("2025-07-21 11:16:58.504374")
        },
        {
            "name": "Lẩu Lòng",
            "nameKo": "내장 샤브샤브",
            "addName": "Lẩu Lòng",
            "addNameKo": "내장 샤브샤브",
            "price": 35000,
            "description": "Lẩu lòng bò với rau và nước dùng đậm đà",
            "descriptionKo": "소고기 국물에 쌀과 내장, 야채 같이 끓인 샤브샤브입니다",
            "image": "/images/lau-long.png",
            "category": "Lẩu",
            "categoryKo": "샤브샤브",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.504705"),
            "updatedAt": new Date("2025-07-21 11:16:58.504709")
        },
        {
            "name": "Lẩu Gà",
            "nameKo": "치킨 샤브샤브",
            "addName": "Lẩu Gà",
            "addNameKo": "치킨 샤브샤브",
            "price": 35000,
            "description": "Lẩu gà với rau, nấm, bún",
            "descriptionKo": "소고기 국물, 야채, 버섯, 치킨, 면 등",
            "image": "/images/lau-ga.png",
            "category": "Lẩu",
            "categoryKo": "샤브샤브",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.504756"),
            "updatedAt": new Date("2025-07-21 11:16:58.504757")
        },
        {
            "name": "Rượu Mai Quế Lộ",
            "nameKo": "매화수",
            "addName": "Rượu Mai Quế Lộ",
            "addNameKo": "매화수",
            "price": 7000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/ruou-mai-que-lo.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.505571"),
            "updatedAt": new Date("2025-07-21 11:16:58.505574")
        },
        {
            "name": "Rượu Chamisul",
            "nameKo": "참이슬",
            "addName": "Rượu Chamisul",
            "addNameKo": "참이슬",
            "price": 6000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/ruou-chamisul.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.505793"),
            "updatedAt": new Date("2025-07-21 11:16:58.505797")
        },
        {
            "name": "Rượu Chum Churum",
            "nameKo": "처음처럼",
            "addName": "Rượu Chum Churum",
            "addNameKo": "처음처럼",
            "price": 6000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/ruou-chum-churum.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.506199"),
            "updatedAt": new Date("2025-07-21 11:16:58.506202")
        },
        {
            "name": "Rượu Jinro",
            "nameKo": "진로",
            "addName": "Rượu Jinro",
            "addNameKo": "진로",
            "price": 6000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/ruou-jinro.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.506452"),
            "updatedAt": new Date("2025-07-21 11:16:58.506454")
        },
        {
            "name": "Bia Cass",
            "nameKo": "카스",
            "addName": "Bia Cass",
            "addNameKo": "카스",
            "price": 6000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/bia-cass.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.506793"),
            "updatedAt": new Date("2025-07-21 11:16:58.506796")
        },
        {
            "name": "Bia Tươi 500ml",
            "nameKo": "생맥주 500ml",
            "addName": "Bia Tươi 500ml",
            "addNameKo": "생맥주 500ml",
            "price": 6000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/bia-tuoi-500ml.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.506833"),
            "updatedAt": new Date("2025-07-21 11:16:58.506834")
        },
        {
            "name": "Bia Tươi 1500ml",
            "nameKo": "생맥주 1500ml",
            "addName": "Bia Tươi 1500ml",
            "addNameKo": "생맥주 1500ml",
            "price": 14000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/bia-tuoi-1500ml.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.506845"),
            "updatedAt": new Date("2025-07-21 11:16:58.506846")
        },
        {
            "name": "Bia Sài Gòn",
            "nameKo": "베트남 맥주 SAI GON",
            "addName": "Bia Sài Gòn",
            "addNameKo": "베트남 맥주 SAI GON",
            "price": 7000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/bia-sai-gon.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.506870"),
            "updatedAt": new Date("2025-07-21 11:16:58.506870")
        },
        {
            "name": "Bia Hà Nội",
            "nameKo": "베트남 맥주 HA NOI",
            "addName": "Bia Hà Nội",
            "addNameKo": "베트남 맥주 HA NOI",
            "price": 7000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/bia-ha-noi.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.506913"),
            "updatedAt": new Date("2025-07-21 11:16:58.506915")
        },
        {
            "name": "Coca",
            "nameKo": "콜라",
            "addName": "Coca",
            "addNameKo": "콜라",
            "price": 2000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/coca.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.506975"),
            "updatedAt": new Date("2025-07-21 11:16:58.506976")
        },
        {
            "name": "Soda",
            "nameKo": "사이다",
            "addName": "Soda",
            "addNameKo": "사이다",
            "price": 2000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/soda.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.506986"),
            "updatedAt": new Date("2025-07-21 11:16:58.506986")
        },
        {
            "name": "Trà Xanh 0 độ",
            "nameKo": "녹차/ Trà Xanh O độ",
            "addName": "Trà Xanh 0 độ",
            "addNameKo": "녹차/ Trà Xanh O độ",
            "price": 3000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/tra-xanh.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.507010"),
            "updatedAt": new Date("2025-07-21 11:16:58.507011")
        },
        {
            "name": "Nước Dừa Lon",
            "nameKo": "코코넛 주스/ Dừa lon",
            "addName": "Nước Dừa Lon",
            "addNameKo": "코코넛 주스/ Dừa lon",
            "price": 6000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/nuoc-dua-lon.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.507071"),
            "updatedAt": new Date("2025-07-21 11:16:58.507075")
        },
        {
            "name": "Dừa Tươi",
            "nameKo": "생코코넛/ Dừa tươi",
            "addName": "Dừa Tươi",
            "addNameKo": "생코코넛/ Dừa tươi",
            "price": 5000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/dua-tuoi.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.507092"),
            "updatedAt": new Date("2025-07-21 11:16:58.507092")
        },
        {
            "name": "Nước Yến",
            "nameKo": "느억엔/ Nước yến",
            "addName": "Nước Yến",
            "addNameKo": "느억엔/ Nước yến",
            "price": 3000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/nuoc-yen.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.507101"),
            "updatedAt": new Date("2025-07-21 11:16:58.507101")
        },
        {
            "name": "Sting",
            "nameKo": "Sting/ Bò cụng",
            "addName": "Sting",
            "addNameKo": "Sting/ Bò cụng",
            "price": 5000,
            "description": "",
            "descriptionKo": "",
            "image": "/images/sting.png",
            "category": "Đồ Uống",
            "categoryKo": "음료",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.507109"),
            "updatedAt": new Date("2025-07-21 11:16:58.507110")
        },
        {
            "name": "Set A",
            "nameKo": "세트 A",
            "addName": "Set A",
            "addNameKo": "세트 A",
            "price": 13500,
            "description": "Phở + Chả Giò + Gỏi Cuốn",
            "descriptionKo": "쌀국수 + 짜조 + 월남쌈 (1인)",
            "image": "/images/set-a.png",
            "category": "Set Menu",
            "categoryKo": "세트메뉴",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.507298"),
            "updatedAt": new Date("2025-07-21 11:16:58.507299")
        },
        {
            "name": "Set B",
            "nameKo": "세트 B",
            "addName": "Set B",
            "addNameKo": "세트 B",
            "price": 23000,
            "description": "Phở + Cơm Rang Hải Sản + 2 Chả Giò",
            "descriptionKo": "쌀국수 + 해물 볶음밥 + 짜조 2ea (2인)",
            "image": "/images/set-b.png",
            "category": "Set Menu",
            "categoryKo": "세트메뉴",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.507315"),
            "updatedAt": new Date("2025-07-21 11:16:58.507316")
        },
        {
            "name": "Set C",
            "nameKo": "세트 C",
            "addName": "Set C",
            "addNameKo": "세트 C",
            "price": 26500,
            "description": "Bún Thịt Nướng + Phở + 2 Chả Giò",
            "descriptionKo": "1분짜 + 쌀국수 + 짜조 2ea (2인)",
            "image": "/images/set-c.png",
            "category": "Set Menu",
            "categoryKo": "세트메뉴",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.507323"),
            "updatedAt": new Date("2025-07-21 11:16:58.507324")
        },
        {
            "name": "Set D",
            "nameKo": "세트 D",
            "addName": "Set D",
            "addNameKo": "세트 D",
            "price": 29500,
            "description": "Bún Chả + Phở + Bánh Mì Thịt",
            "descriptionKo": "분짜 + 쌀국수 + 고기반미 (2-3인)",
            "image": "/images/set-d.png",
            "category": "Set Menu",
            "categoryKo": "세트메뉴",
            "available": true,
            "sales": 0,
            "visible": true,
            "createdAt": new Date("2025-07-21 11:16:58.507330"),
            "updatedAt": new Date("2025-07-21 11:16:58.507331")
        }
    ];

    for (const productData of products) {
        // Check if product exists by name instead of ID since IDs are auto-generated
        const existingProduct = await productRepository.findOne({ where: { name: productData.name } });
        if (!existingProduct) {
            // Get the category ID from the map
            const categoryId = categoryIdMap.get(productData.category);
            if (categoryId) {
                const productToSave = {
                    ...productData,
                    categoryId: categoryId
                };
                const product = productRepository.create(productToSave);
                await productRepository.save(product);
                console.log(`Created product: ${product.name}`);
            } else {
                console.log(`Category not found for product: ${productData.name}`);
            }
        } else {
            console.log(`Product already exists: ${existingProduct.name}`);
        }
    }

    console.log('Database seeding completed!');
} 