/** SePay qr.sepay.vn bank aliases (BIN, code, short_name → short_name). */
export const SEPAY_BANK_ALIASES: Record<string, string> = {
  '422589': 'CIMB',
  '458761': 'HSBC',
  '796500': 'DBSBank',
  '801011': 'Nonghyup',
  '970400': 'SaigonBank',
  '970403': 'Sacombank',
  '970405': 'Agribank',
  '970406': 'DongABank',
  '970407': 'Techcombank',
  '970408': 'GPBank',
  '970409': 'BacABank',
  '970410': 'StandardChartered',
  '970412': 'PVcomBank',
  '970414': 'Oceanbank',
  '970415': 'VietinBank',
  '970416': 'ACB',
  '970418': 'BIDV',
  '970419': 'NCB',
  '970421': 'VRB',
  '970422': 'MBBank',
  '970423': 'TPBank',
  '970424': 'ShinhanBank',
  '970425': 'ABBANK',
  '970426': 'MSB',
  '970427': 'VietABank',
  '970428': 'NamABank',
  '970429': 'SCB',
  '970430': 'PGBank',
  '970431': 'Eximbank',
  '970432': 'VPBank',
  '970433': 'VietBank',
  '970434': 'IndovinaBank',
  '970436': 'Vietcombank',
  '970437': 'HDBank',
  '970438': 'BaoVietBank',
  '970439': 'PublicBank',
  '970440': 'SeABank',
  '970441': 'VIB',
  '970442': 'HongLeong',
  '970443': 'SHB',
  '970444': 'CBBank',
  '970446': 'COOPBANK',
  '970448': 'OCB',
  '970449': 'LienVietPostBank',
  '970452': 'KienLongBank',
  '970454': 'VietCapitalBank',
  '970455': 'IBK Bank',
  '970456': 'IBK Bank',
  '970457': 'Woori',
  '970458': 'UnitedOverseas',
  '970462': 'KookminHN',
  '970463': 'KookminHCM',
  '971025': 'MoMo',
  '971133': 'PVcomBankPay',
  ABB: 'ABBANK',
  ABBANK: 'ABBANK',
  ACB: 'ACB',
  AGRIBANK: 'Agribank',
  BAB: 'BacABank',
  BACABANK: 'BacABank',
  BAOVIETBANK: 'BaoVietBank',
  BIDV: 'BIDV',
  BVB: 'BaoVietBank',
  CBB: 'CBBank',
  CBBANK: 'CBBank',
  CIMB: 'CIMB',
  COOPBANK: 'COOPBANK',
  DBS: 'DBSBank',
  DBSBANK: 'DBSBank',
  DOB: 'DongABank',
  DONGABANK: 'DongABank',
  EIB: 'Eximbank',
  EXIMBANK: 'Eximbank',
  GPB: 'GPBank',
  GPBANK: 'GPBank',
  HDB: 'HDBank',
  HDBANK: 'HDBank',
  HLBVN: 'HongLeong',
  HONGLEONG: 'HongLeong',
  HSBC: 'HSBC',
  'IBK BANK': 'IBK Bank',
  IBKHCM: 'IBK Bank',
  IBKHN: 'IBK Bank',
  ICB: 'VietinBank',
  INDOVINABANK: 'IndovinaBank',
  IVB: 'IndovinaBank',
  KBHCM: 'KookminHCM',
  KBHN: 'KookminHN',
  KIENLONGBANK: 'KienLongBank',
  KLB: 'KienLongBank',
  KOOKMINHCM: 'KookminHCM',
  KOOKMINHN: 'KookminHN',
  LIENVIETPOSTBANK: 'LienVietPostBank',
  LPB: 'LienVietPostBank',
  MB: 'MBBank',
  MBBANK: 'MBBank',
  MOMO: 'MoMo',
  MSB: 'MSB',
  NAB: 'NamABank',
  NAMABANK: 'NamABank',
  NCB: 'NCB',
  NHBHN: 'Nonghyup',
  NONGHYUP: 'Nonghyup',
  OCB: 'OCB',
  OCEANBANK: 'Oceanbank',
  PBVN: 'PublicBank',
  PGB: 'PGBank',
  PGBANK: 'PGBank',
  PUBLICBANK: 'PublicBank',
  PVCB: 'PVcomBank',
  PVCBP: 'PVcomBankPay',
  PVCOMBANK: 'PVcomBank',
  PVCOMBANKPAY: 'PVcomBankPay',
  SACOMBANK: 'Sacombank',
  SAIGONBANK: 'SaigonBank',
  SCB: 'SCB',
  SCVN: 'StandardChartered',
  SEAB: 'SeABank',
  SEABANK: 'SeABank',
  SGICB: 'SaigonBank',
  SHB: 'SHB',
  SHBVN: 'ShinhanBank',
  SHINHANBANK: 'ShinhanBank',
  STANDARDCHARTERED: 'StandardChartered',
  STB: 'Sacombank',
  TCB: 'Techcombank',
  TECHCOMBANK: 'Techcombank',
  TPB: 'TPBank',
  TPBANK: 'TPBank',
  UNITEDOVERSEAS: 'UnitedOverseas',
  UOB: 'UnitedOverseas',
  VAB: 'VietABank',
  VBA: 'Agribank',
  VCB: 'Vietcombank',
  VCCB: 'VietCapitalBank',
  VIB: 'VIB',
  VIETABANK: 'VietABank',
  VIETBANK: 'VietBank',
  VIETCAPITALBANK: 'VietCapitalBank',
  VIETCOMBANK: 'Vietcombank',
  VIETINBANK: 'VietinBank',
  VPB: 'VPBank',
  VPBANK: 'VPBank',
  VRB: 'VRB',
  WOORI: 'Woori',
  WVN: 'Woori',
};

/** Map BIN (970422) or bank code (MB) to SePay short_name (MBBank). */
export function normalizeSepayBankCode(raw?: string | null): string | undefined {
  const trimmed = raw?.trim();
  if (!trimmed) return undefined;
  return SEPAY_BANK_ALIASES[trimmed.toUpperCase()] ?? trimmed;
}
